// MovieDuels MP: player/bot model -> SP animation style (playerState_t.animStyle, bg_public.h animStyle_t).
// Generated from the MP menu characters (ui_mdchars.h: model, skin, SP npc) and the SP npc files
// (ext_data/npcs/*.npc "animationstyle CS_*"); CS_DEFAULT rows are left out. G_AnimStyleForModel: the exact model
// string ("folder" or "folder/skin"), else the folder.

typedef struct modelAnimStyle_s
{
	const char* model;
	animStyle_t animStyle;
} modelAnimStyle_t;

static const modelAnimStyle_t modelAnimStyles[] =
{
	{ "atris", ANIMSTYLE_KOTOR },	// Atris [Jedi Master]
	{ "bastila", ANIMSTYLE_KOTOR },	// Bastila Shan [Jedi Battle Robes]
	{ "bastila/robe", ANIMSTYLE_KOTOR },	// Bastila Shan [Jedi Battle Robes - Hooded]
	{ "jedi_kotor_fem/bastila", ANIMSTYLE_KOTOR },	// Bastila Shan [Dark Jedi]
	{ "jedi_kotor/dorak", ANIMSTYLE_KOTOR },	// Dorak [Jedi]
	{ "jedi_kotor/default_new", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/deadeye", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/gerevick", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/marl", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/jedi1", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/jedi2", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/jedi3", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/jedi4", ANIMSTYLE_KOTOR },	// Jedi Knight [KOTOR]
	{ "jedi_kotor/twilek", ANIMSTYLE_KOTOR },	// Jedi Knight [Twilek]
	{ "sith_eradicator/jedi", ANIMSTYLE_MOVIEDUELS },	// Jedi Warrior [Jedi]
	{ "jolee_bindo", ANIMSTYLE_KOTOR },	// Jolee Bindo [Jedi]
	{ "jedi_kotor/jolee", ANIMSTYLE_KOTOR },	// Jolee Bindo [Jedi]
	{ "juhani", ANIMSTYLE_KOTOR },	// Juhani [Jedi]
	{ "juhani/alt", ANIMSTYLE_KOTOR },	// Juhani [Jedi - Alternative]
	{ "jedi_kotor_fem", ANIMSTYLE_KOTOR },	// Juhani [Jedi - Robed]
	{ "jedi_tor", ANIMSTYLE_KOTOR },	// Kao Cen Darach [Jedi Master]
	{ "kreia", ANIMSTYLE_KOTOR },	// Kreia [Jedi]
	{ "meetra", ANIMSTYLE_KOTOR },	// Meetra Surik [Jedi]
	{ "meetra/robed", ANIMSTYLE_KOTOR },	// Meetra Surik [Jedi - Robed]
	{ "meetra/hooded", ANIMSTYLE_KOTOR },	// Meetra Surik [Jedi - Hooded]
	{ "revan_jedi", ANIMSTYLE_KOTOR },	// Revan [Star Forge - Masked]
	{ "revan_jedi/nomask", ANIMSTYLE_KOTOR },	// Revan [Star Forge - Unmasked]
	{ "revan_jedi/nomask_nohood", ANIMSTYLE_KOTOR },	// Revan [Star Forge]
	{ "revan_mw", ANIMSTYLE_KOTOR },	// Revan [Mandalorian Wars - Masked]
	{ "revan_mw/nomask", ANIMSTYLE_KOTOR },	// Revan [Mandalorian Wars - Unmasked]
	{ "revan_mw/nomask_nohood", ANIMSTYLE_KOTOR },	// Revan [Mandalorian Wars]
	{ "revan_prekotor", ANIMSTYLE_KOTOR },	// Revan [Cathar - Masked]
	{ "revan_prekotor/nomask", ANIMSTYLE_KOTOR },	// Revan [Cathar - Unmasked]
	{ "revan_prekotor/nomask_nohood", ANIMSTYLE_KOTOR },	// Revan [Cathar]
	{ "jedi_robe_revan", ANIMSTYLE_KOTOR },	// Revan [Jedi]
	{ "jedi_robe_revan/default2", ANIMSTYLE_KOTOR },	// Revan [Jedi]
	{ "jedi_robe_revan/default3", ANIMSTYLE_KOTOR },	// Revan [Jedi]
	{ "jedi_robe_revan/default4", ANIMSTYLE_KOTOR },	// Revan [Jedi]
	{ "jedi_robe_revan/default5", ANIMSTYLE_KOTOR },	// Revan [Jedi]
	{ "jedi_robe_revan/student", ANIMSTYLE_KOTOR },	// Revan [Student]
	{ "vandar", ANIMSTYLE_YODA },	// Vandar Tokare [Jedi]
	{ "jedi_tor/ven", ANIMSTYLE_KOTOR },	// Ven Zallow [Jedi]
	{ "jedi_kotor/vrook", ANIMSTYLE_KOTOR },	// Vrook Lamar [Jedi]
	{ "jedi_kotor/zhar", ANIMSTYLE_KOTOR },	// Zhar Lestin [Jedi]
	{ "thexan/arcann", ANIMSTYLE_MOVIEDUELS },	// Arcann [KOTOR]
	{ "arcann", ANIMSTYLE_MOVIEDUELS },	// Arcann [KOTOR - Masked]
	{ "darkjedi", ANIMSTYLE_KOTOR },	// Dark Jedi [KOTOR]
	{ "darkjedi/default2", ANIMSTYLE_KOTOR },	// Dark Jedi [KOTOR]
	{ "darkjedi/default3", ANIMSTYLE_KOTOR },	// Dark Jedi [KOTOR]
	{ "darthbane", ANIMSTYLE_MOVIEDUELS },	// Darth Bane [KOTOR]
	{ "darthbane/alt", ANIMSTYLE_MOVIEDUELS },	// Darth Bane [KOTOR - Alternative]
	{ "darthbane/armor", ANIMSTYLE_MOVIEDUELS },	// Darth Bane [KOTOR - Armor]
	{ "darthbane/armor_alt", ANIMSTYLE_MOVIEDUELS },	// Darth Bane [KOTOR - Alternative Armor]
	{ "darthbane/shirtless", ANIMSTYLE_MOVIEDUELS },	// Darth Bane [KOTOR - Shirtless]
	{ "darthbane2", ANIMSTYLE_MOVIEDUELS },	// Darth Bane [TCW - Armor]
	{ "darthmalgus", ANIMSTYLE_VADER },	// Darth Malgus [Sith]
	{ "darthmalgus/hood", ANIMSTYLE_VADER },	// Darth Malgus [Sith - Hooded]
	{ "darthmalgus/nocape", ANIMSTYLE_VADER },	// Darth Malgus [Sith - No Cape]
	{ "darthmalgus/lord", ANIMSTYLE_VADER },	// Darth Malgus [Sith Lord]
	{ "darthmalgus/lorddm", ANIMSTYLE_VADER },	// Darth Malgus [Sith Lord - Damaged]
	{ "darthmalgus/nomask", ANIMSTYLE_VADER },	// Darth Malgus [Sith Lord - Young]
	{ "darthmalgus/nomask_hood", ANIMSTYLE_VADER },	// Darth Malgus [Sith Lord - Young Hooded]
	{ "darthmalgus_onslaught", ANIMSTYLE_VADER },	// Darth Malgus [Onslaught]
	{ "darthmalgus_onslaught/nomask", ANIMSTYLE_VADER },	// Darth Malgus [Onslaught - No Mask]
	{ "darthmalgus_onslaught/nocape", ANIMSTYLE_VADER },	// Darth Malgus [Onslaught - No Cape]
	{ "malak", ANIMSTYLE_KOTOR },	// Darth Malak [Sith Lord]
	{ "malak/mouth_damaged", ANIMSTYLE_KOTOR },	// Darth Malak [Sith Lord - Damaged]
	{ "nihilus", ANIMSTYLE_MOVIEDUELS },	// Darth Nihilus [Sith]
	{ "nihilus/new", ANIMSTYLE_MOVIEDUELS },	// Darth Nihilus [Sith - Alternative]
	{ "nihilus/new2", ANIMSTYLE_MOVIEDUELS },	// Darth Nihilus [Sith - Alternative]
	{ "revan/nomask", ANIMSTYLE_KOTOR },	// Darth Revan [Hooded - Unmasked]
	{ "revan/nomask_nohood", ANIMSTYLE_KOTOR },	// Darth Revan [Unmasked]
	{ "revan_reborn", ANIMSTYLE_KOTOR },	// Revan Reborn [Hooded - Masked]
	{ "revan_reborn/nomask", ANIMSTYLE_KOTOR },	// Revan Reborn [Hooded - Unmasked]
	{ "revan_reborn/nomask_nohood", ANIMSTYLE_KOTOR },	// Revan Reborn [Unmasked]
	{ "sion", ANIMSTYLE_MOVIEDUELS },	// Darth Sion [KOTOR]
	{ "sion/k2", ANIMSTYLE_MOVIEDUELS },	// Darth Sion [KOTOR - Alternative]
	{ "sion/tfu", ANIMSTYLE_MOVIEDUELS },	// Darth Sion [TFU]
	{ "traya", ANIMSTYLE_KOTOR },	// Darth Traya [Sith]
	{ "vindican", ANIMSTYLE_KOTOR },	// Darth Vindican [KOTOR]
	{ "vindican/hood", ANIMSTYLE_KOTOR },	// Darth Vindican [KOTOR - Hooded]
	{ "hk47", ANIMSTYLE_BATTLEDROID },	// HK 47 [KOTOR]
	{ "sith_officer/jorak", ANIMSTYLE_KOTOR },	// Jorak Uln [KOTOR]
	{ "scourge", ANIMSTYLE_KOTOR },	// Lord Scourge [KOTOR]
	{ "sith_officer/saul", ANIMSTYLE_KOTOR },	// Saul Karath [KOTOR]
	{ "sith_eradicator", ANIMSTYLE_MOVIEDUELS },	// Sith Eradicator [KOTOR]
	{ "sith_officer", ANIMSTYLE_KOTOR },	// Sith Officer [KOTOR]
	{ "sith_officer/default2", ANIMSTYLE_KOTOR },	// Sith Officer [KOTOR]
	{ "sith_officer/officer2", ANIMSTYLE_KOTOR },	// Sith Officer [KOTOR]
	{ "sith_officer/officer_afro", ANIMSTYLE_KOTOR },	// Sith Officer [KOTOR]
	{ "sith_officer/officer_asian", ANIMSTYLE_KOTOR },	// Sith Officer [KOTOR]
	{ "jedi_kotor/baturem", ANIMSTYLE_KOTOR },	// Sith Warrior [KOTOR]
	{ "jedi_kotor/sith1", ANIMSTYLE_KOTOR },	// Sith Warrior [KOTOR]
	{ "jedi_kotor/sith2", ANIMSTYLE_KOTOR },	// Sith Warrior [KOTOR]
	{ "jedi_kotor/sith3", ANIMSTYLE_KOTOR },	// Sith Warrior [KOTOR]
	{ "thexan", ANIMSTYLE_MOVIEDUELS },	// Thexan [KOTOR]
	{ "sith_officer/uthar", ANIMSTYLE_KOTOR },	// Uthar Wynn [KOTOR]
	{ "visas", ANIMSTYLE_KOTOR },	// Visas Marr [KOTOR]
	{ "visas/dark", ANIMSTYLE_KOTOR },	// Visas Marr [KOTOR - Alternative]
	{ "yuthura", ANIMSTYLE_KOTOR },	// Yuthura Ban [KOTOR]
	{ "aayla", ANIMSTYLE_MOVIEDUELS },	// Aayla Secura [Episode I-III]
	{ "adi_gallia/robed", ANIMSTYLE_MOVIEDUELS },	// Adi Gallia [Episode I-III]
	{ "adi_gallia/cw", ANIMSTYLE_MOVIEDUELS },	// Adi Gallia [General]
	{ "agen_kolar", ANIMSTYLE_MOVIEDUELS },	// Agen Kolar [Episode I-III]
	{ "agen_kolar/robed", ANIMSTYLE_MOVIEDUELS },	// Agen Kolar [Robed]
	{ "ahsoka", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Padawan]
	{ "ahsoka/padawan", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Padawan]
	{ "ahsoka/tcw", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Padawan]
	{ "ahsoka/eva", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Eva Suit]
	{ "ahsoka/totj", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TOTJ]
	{ "ahsoka/mortis", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Mortis]
	{ "ahsoka_s7", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Season 7]
	{ "ahsoka_s7/robe", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Season 7 Robed]
	{ "ahsoka_s7/young", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Season 7 Live Action]
	{ "ahsoka_s7/young_robe", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [TCW - Season 7 Live Action Robed]
	{ "ahsoka_rebels", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [Rebels]
	{ "ahsoka_rebels/poncho", ANIMSTYLE_GALEN_MAREK },	// Ahsoka Tano [Rebels - Fulcrum Poncho]
	{ "anakin", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [Episode III]
	{ "anakin/robed", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [Episode III - Robed]
	{ "anakin/hood", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [Episode III - Hooded]
	{ "anakin/shirtless_robe", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [Episode III - Pyjama]
	{ "anakin/shirtless", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [Episode III - Shirtless]
	{ "anakin_ep2", ANIMSTYLE_MOVIEDUELS },	// Anakin Skywalker [Episode II]
	{ "anakin_ep2/robed", ANIMSTYLE_MOVIEDUELS },	// Anakin Skywalker [Episode II - Robed]
	{ "anakin_ep2/hooded", ANIMSTYLE_MOVIEDUELS },	// Anakin Skywalker [Episode II - Hooded]
	{ "anakin/tcw", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [TCW]
	{ "anakin/tcw_caped", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [TCW - Cape]
	{ "anakin/tcw_s3", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [TCW - Season 3]
	{ "anakin/tcwa", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [TCW Animated]
	{ "anakin/tcwa_robed", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [TCW Animated - Robed]
	{ "anakin/tcwa_hooded", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [TCW Animated - Hooded]
	{ "anakin/cw", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [CW 2003]
	{ "anakin/cw_caped", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [CW 2003 - Cape]
	{ "anakin/jtrial", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [CW 2003 - Jedi Trials]
	{ "anakin/swolo", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [CW 2003 - Nelvaan Trials]
	{ "anakin/ep2_cw", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [CW 2003 - Yavin]
	{ "anakin/ep2_cw_bw", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [CW 2003 - Yavin Battleworn]
	{ "barriss_offee", ANIMSTYLE_MOVIEDUELS },	// Barris Offee [TCW]
	{ "bolla_ropal", ANIMSTYLE_MOVIEDUELS },	// Bolla Ropal [TCW]
	{ "bultar", ANIMSTYLE_MOVIEDUELS },	// Bultar Swan [Episode II-III]
	{ "bultar/robed", ANIMSTYLE_MOVIEDUELS },	// Bultar Swan [Episode II-III - Robed]
	{ "cin_drallig", ANIMSTYLE_MOVIEDUELS },	// Cin Drallig [TCW - Episode III]
	{ "cin_drallig/cw", ANIMSTYLE_MOVIEDUELS },	// Cin Drallig [TCW]
	{ "cin_drallig/old", ANIMSTYLE_MOVIEDUELS },	// Cin Drallig [Legends]
	{ "clonetrooper_p2/501_rex", ANIMSTYLE_CLONETROOPER },	// Captain Rex [TCW]
	{ "clonetrooper_p2/212_cody", ANIMSTYLE_CLONETROOPER },	// Commander Cody [TCW]
	{ "clonetrooper_p2/fox", ANIMSTYLE_CLONETROOPER },	// Commander Fox [TCW]
	{ "clonetrooper_p2/91_neyo", ANIMSTYLE_CLONETROOPER },	// Commander Neyo [TCW]
	{ "clonetrooper_p2/332_vaughn", ANIMSTYLE_CLONETROOPER },	// Commander Vaughn [TCW]
	{ "clonetrooper_p2/fives", ANIMSTYLE_CLONETROOPER },	// Fives [TCW]
	{ "clonerc2/commando", ANIMSTYLE_CLONETROOPER },	// Clone Commando [Night Ops Armor]
	{ "clonerc2/boss", ANIMSTYLE_CLONETROOPER },	// Boss [Commando]
	{ "clonerc2/fixer", ANIMSTYLE_CLONETROOPER },	// Fixer [Commando]
	{ "clonerc2/gregor", ANIMSTYLE_CLONETROOPER },	// Gregor [Commando]
	{ "clonerc2/scorch", ANIMSTYLE_CLONETROOPER },	// Scorch [Commando]
	{ "clonerc2/sev", ANIMSTYLE_CLONETROOPER },	// Sev [Commando]
	{ "clonetrooper_p1", ANIMSTYLE_CLONETROOPER },	// Clone Trooper [Phase 1]
	{ "clonetrooper_p2/212", ANIMSTYLE_CLONETROOPER },	// Clone Trooper [212th Battalion]
	{ "clonetrooper_p2/212_airborne", ANIMSTYLE_CLONETROOPER },	// Clone Paratrooper [212th Battalion]
	{ "clonetrooper_p2/13", ANIMSTYLE_CLONETROOPER },	// Clone Trooper [13th Battalion]
	{ "clonetrooper_p2/airborne_rgb", ANIMSTYLE_CLONETROOPER },	// Clone Sharpshooter [501st Legion]
	{ "clonetrooper_p2/501", ANIMSTYLE_CLONETROOPER },	// Clone Trooper [501st Legion]
	{ "clonetrooper_p2/deviss_rgb", ANIMSTYLE_CLONETROOPER },	// Clone Commander [501st Legion]
	{ "clonetrooper_p2/shock", ANIMSTYLE_CLONETROOPER },	// Clone Shock Trooper [Shock Trooper]
	{ "clonetrooper_p2/327_deviss", ANIMSTYLE_CLONETROOPER },	// Commander Deviss [TCW]
	{ "clonetrooper_p2/332", ANIMSTYLE_CLONETROOPER },	// Clone Trooper [332nd Company]
	{ "clonetrooper_p2/327", ANIMSTYLE_CLONETROOPER },	// Clone Trooper [327th Star Corps]
	{ "clonetrooper_p2/shadow", ANIMSTYLE_CLONETROOPER },	// Clone Shadow Trooper [Shadow Trooper]
	{ "clonemarine", ANIMSTYLE_CLONETROOPER },	// Galactic Marine [21st Nova Corps]
	{ "coleman", ANIMSTYLE_MOVIEDUELS },	// Coleman Trebor [Episode I-II]
	{ "depabillaba_tcw/robed", ANIMSTYLE_MOVIEDUELS },	// Depa Billaba [TCW - Robed]
	{ "depabillaba_tcw/hooded", ANIMSTYLE_MOVIEDUELS },	// Depa Billaba [TCW - Hooded]
	{ "depabillaba", ANIMSTYLE_MOVIEDUELS },	// Depa Billaba [Episode I-III]
	{ "eekar", ANIMSTYLE_MOVIEDUELS },	// Eekar Oki [TCW]
	{ "even_piell", ANIMSTYLE_MOVIEDUELS },	// Even Piell [Episode I-III]
	{ "falon_grey", ANIMSTYLE_MOVIEDUELS },	// Falon Grey [Battlefront]
	{ "sirch/robed", ANIMSTYLE_MOVIEDUELS },	// Fi-Ek Sirch [Episode II]
	{ "foul_moudama", ANIMSTYLE_MOVIEDUELS },	// Foul Moudama [TCW]
	{ "halsey/cw", ANIMSTYLE_MOVIEDUELS },	// Halsey [TCW]
	{ "ima_gundi", ANIMSTYLE_OBIWAN_EP3 },	// Ima-Gun Di [TCW]
	{ "joopi_she/robed", ANIMSTYLE_MOVIEDUELS },	// J'oopi She [TCW]
	{ "jedi_spanki/|head_b4|torso_a4|lower_f1", ANIMSTYLE_MOVIEDUELS },	// Jedi Master [Jedi]
	{ "jedi_spanki/|head_b2|torso_a3|lower_a1", ANIMSTYLE_MOVIEDUELS },	// Jedi Master [Jedi]
	{ "jedi_spanki/|head_d4|torso_b2|lower_b1", ANIMSTYLE_MOVIEDUELS },	// Jedi Veteran [Jedi - Dual Lightsabers]
	{ "jedi_spanki/|head_f1|torso_b4|lower_c1", ANIMSTYLE_MOVIEDUELS },	// Jedi Veteran [Jedi - Dual Lightsabers]
	{ "jedi_spanki/|head_f1|torso_f2|lower_g1", ANIMSTYLE_MOVIEDUELS },	// Jedi Knight [Jedi]
	{ "jedi_female1/|head_c2|torso_d2|lower_f1", ANIMSTYLE_MOVIEDUELS },	// Jedi Knight [Jedi - Dual Lightsabers]
	{ "zabrak_rots", ANIMSTYLE_MOVIEDUELS },	// Jedi Knight [Jedi]
	{ "jedi_spanki/|head_d1|torso_g1|lower_d1", ANIMSTYLE_MOVIEDUELS },	// Jedi Knight [Jedi]
	{ "jedi_spanki/|head_e5|torso_c1|lower_d1", ANIMSTYLE_MOVIEDUELS },	// Jedi Padawan [Jedi]
	{ "jedi_spanki/|head_d5|torso_f1|lower_g1", ANIMSTYLE_MOVIEDUELS },	// Jedi Padawan [Jedi]
	{ "jedi_female1/|head_d3|torso_f1|lower_e1", ANIMSTYLE_MOVIEDUELS },	// Jedi Padawan [Jedi]
	{ "jtguard", ANIMSTYLE_MOVIEDUELS },	// Jedi Temple Guard [TCW]
	{ "gi_rebels/jtguard", ANIMSTYLE_COUNT_DOOKU },	// Jedi Temple Guard [Rebels]
	{ "jocasta", ANIMSTYLE_MOVIEDUELS },	// Jocasta Nu [Episode I-III]
	{ "kelleran_beq/robed", ANIMSTYLE_MOVIEDUELS },	// Kelleran Beq [Jedi]
	{ "ki_adi_mundi", ANIMSTYLE_MOVIEDUELS },	// Ki-Adi Mundi [Episode I-III]
	{ "fisto", ANIMSTYLE_MOVIEDUELS },	// Kit Fisto [Episode I-III]
	{ "fisto/robed", ANIMSTYLE_MOVIEDUELS },	// Kit Fisto [Episode I-III - Robed]
	{ "fisto/cw", ANIMSTYLE_MOVIEDUELS },	// Kit Fisto [General]
	{ "kitfisto_cw", ANIMSTYLE_MOVIEDUELS },	// Kit Fisto [Shirtless]
	{ "knox", ANIMSTYLE_MOVIEDUELS },	// Knox [TCW]
	{ "koffi_arana/robed", ANIMSTYLE_MOVIEDUELS },	// Koffi Arana [Jedi]
	{ "luminara", ANIMSTYLE_MOVIEDUELS },	// Luminara Unduli [Episode I-III]
	{ "jedi_nikto", ANIMSTYLE_MOVIEDUELS },	// Ma'kis'shaalas [TCW]
	{ "jedi_nikto/robed", ANIMSTYLE_MOVIEDUELS },	// Ma'kis'shaalas [Robed]
	{ "macewindu", ANIMSTYLE_MACE_WINDU },	// Mace Windu [Episode II-III]
	{ "macewindu/robed", ANIMSTYLE_MACE_WINDU },	// Mace Windu [Episode II-III - Robed]
	{ "macewindu/hooded", ANIMSTYLE_MACE_WINDU },	// Mace Windu [Episode II-III - Hooded]
	{ "macewindu/ghost", ANIMSTYLE_MACE_WINDU },	// Mace Windu [Force Ghost]
	{ "macewindu/cw", ANIMSTYLE_MACE_WINDU },	// Mace Windu [TCW - General]
	{ "macewindu_cw", ANIMSTYLE_MACE_WINDU },	// Mace Windu [CW - General]
	{ "macewindu/totj", ANIMSTYLE_MACE_WINDU },	// Mace Windu [Tales of the Jedi]
	{ "micah_giiett/robed", ANIMSTYLE_MOVIEDUELS },	// Micah Giiett [TCW]
	{ "nahdar", ANIMSTYLE_MOVIEDUELS },	// Nahdar Vebb [TCW]
	{ "nahdar/robed", ANIMSTYLE_MOVIEDUELS },	// Nahdar Vebb [Robed]
	{ "obiwan_ep3", ANIMSTYLE_OBIWAN_EP3 },	// Obi-Wan Kenobi [Episode III]
	{ "obiwan_ep3/robed", ANIMSTYLE_OBIWAN_EP3 },	// Obi-Wan Kenobi [Episode III - Robed]
	{ "obiwan_ep3/hood", ANIMSTYLE_OBIWAN_EP3 },	// Obi-Wan Kenobi [Episode III - Hooded]
	{ "obiwan_ep3/bw", ANIMSTYLE_OBIWAN_EP3 },	// Obi-Wan Kenobi [Episode III - Mustafar Worn]
	{ "obiwan_ep2", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [Episode II]
	{ "obiwan_ep2/robed", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [Episode II - Robed]
	{ "obiwan_ep2/hooded", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [Episode II - Hooded]
	{ "obiwan_ep1", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [Episode I]
	{ "obiwan_ep1/robed", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [Episode I - Robed]
	{ "obiwan_ep1/hooded", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [Episode I - Hooded]
	{ "obiwan_jabiim", ANIMSTYLE_BENKENOBI },	// Obi-Wan Kenobi [Jabiim]
	{ "obiwan_jabiim/robed", ANIMSTYLE_BENKENOBI },	// Obi-Wan Kenobi [Jabiim - Robed]
	{ "obiwan_jabiim/defaultb", ANIMSTYLE_BENKENOBI },	// Obi-Wan Kenobi [Pre-ANH]
	{ "obiwan_jabiim/robedc", ANIMSTYLE_BENKENOBI },	// Obi-Wan Kenobi [Pre-ANH - Desert]
	{ "obiwan_ep3/exile", ANIMSTYLE_OBIWAN_EP3 },	// Obi-Wan Kenobi [Exiled]
	{ "obiwan_tcw", ANIMSTYLE_OBIWAN_EP3 },	// Obi-Wan Kenobi [TCW - General]
	{ "obiwan_cw", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [CW - General]
	{ "obiwan_cw/helmet", ANIMSTYLE_OBIWAN },	// Obi-Wan Kenobi [CW - General]
	{ "oppo_rancisis", ANIMSTYLE_MOVIEDUELS },	// Oppo Rancisis [Episode I-III]
	{ "ongree/robed", ANIMSTYLE_MOVIEDUELS },	// Pablo Jill [Episode I-III]
	{ "redathgom/robed", ANIMSTYLE_MOVIEDUELS },	// Que-Mars Redath-Gom [TCW]
	{ "quigon", ANIMSTYLE_QUI_GON_JINN },	// Qui-Gon Jinn [Episode I]
	{ "quigon/robed", ANIMSTYLE_QUI_GON_JINN },	// Qui-Gon Jinn [Episode I - Robed]
	{ "quigon/poncho", ANIMSTYLE_QUI_GON_JINN },	// Qui-Gon Jinn [Episode I - Poncho]
	{ "quigon/ghost", ANIMSTYLE_QUI_GON_JINN },	// Qui-Gon Jinn [Force Ghost]
	{ "quinlan_vos", ANIMSTYLE_MOVIEDUELS },	// Quinlan Vos [TCW]
	{ "saesee_tiin", ANIMSTYLE_MOVIEDUELS },	// Saesee Tiin [Episode I-III]
	{ "saesee_tiin/robed", ANIMSTYLE_MOVIEDUELS },	// Saesee Tiin [Episode I-III - Robed]
	{ "sarissa_jeng", ANIMSTYLE_MOVIEDUELS },	// Sarissa Jeng [TCW]
	{ "shaak_ti", ANIMSTYLE_MOVIEDUELS },	// Shaak Ti [Episode I-III]
	{ "shaakti_tfu", ANIMSTYLE_MOVIEDUELS },	// Shaak Ti [Exiled - Felucia]
	{ "jtguard_boss", ANIMSTYLE_MOVIEDUELS },	// Shakkra Kien [TCW]
	{ "sora_bulq", ANIMSTYLE_MOVIEDUELS },	// Sora Bulq [TCW]
	{ "serraketo", ANIMSTYLE_MOVIEDUELS },	// Serra Keto [Jedi]
	{ "stass_allie", ANIMSTYLE_MOVIEDUELS },	// Stass Allie [Episode I-III]
	{ "stass_allie/robed", ANIMSTYLE_MOVIEDUELS },	// Stass Allie [Robed]
	{ "tarados_gon", ANIMSTYLE_MOVIEDUELS },	// Tarados Gon [TCW]
	{ "tera_sinube", ANIMSTYLE_MOVIEDUELS },	// Tera Sinube [TCW]
	{ "thongla_jur", ANIMSTYLE_MOVIEDUELS },	// Thongla Jur [TCW]
	{ "tiplee/tiplar", ANIMSTYLE_MOVIEDUELS },	// Tiplar [TCW]
	{ "tiplee", ANIMSTYLE_MOVIEDUELS },	// Tiplee [TCW]
	{ "tsuichoi", ANIMSTYLE_YODA },	// Tsui Choi [TCW]
	{ "yaddle", ANIMSTYLE_YODA },	// Yaddle [Episode I]
	{ "yarael", ANIMSTYLE_MOVIEDUELS },	// Yarael Poof [Episode I-III]
	{ "yoda", ANIMSTYLE_YODA },	// Yoda [Episode III]
	{ "yoda/ep2", ANIMSTYLE_YODA },	// Yoda [Episode I-II]
	{ "yoda/hr", ANIMSTYLE_YODA },	// Yoda [High Republic]
	{ "yoda/cw", ANIMSTYLE_YODA },	// Yoda [Clone Wars]
	{ "yoda/ot", ANIMSTYLE_YODA },	// Yoda [Episode V]
	{ "yoda/ghost", ANIMSTYLE_YODA },	// Yoda [Force Ghost]
	{ "zett_jukassa", ANIMSTYLE_MOVIEDUELS },	// Zett Jukassa [Episode III]
	{ "asajj", ANIMSTYLE_MOVIEDUELS },	// Asajj Ventress [TCW]
	{ "asajj/ns", ANIMSTYLE_MOVIEDUELS },	// Asajj Ventress [Nightsister]
	{ "asajj_bh", ANIMSTYLE_MOVIEDUELS },	// Asajj Ventress [Bounty Hunter]
	{ "asajj_bh/disguise", ANIMSTYLE_MOVIEDUELS },	// Asajj Ventress [Disguised]
	{ "battledroid/security", ANIMSTYLE_BATTLEDROID },	// B1 Battle Droid [Security]
	{ "battledroid/pilot", ANIMSTYLE_BATTLEDROID },	// B1 Battle Droid [Pilot]
	{ "battledroid/comm", ANIMSTYLE_BATTLEDROID },	// B1 Battle Droid [Commander]
	{ "battledroid/sniper", ANIMSTYLE_BATTLEDROID },	// B1 Battle Droid [Sniper]
	{ "battledroid/geonosis", ANIMSTYLE_BATTLEDROID },	// B1 Battle Droid [Geonosis]
	{ "clonetrooper_p2/assassin", ANIMSTYLE_CLONETROOPER },	// Clone Assassin [Jedi Temple]
	{ "dooku", ANIMSTYLE_COUNT_DOOKU },	// Count Dooku [Episode II-III]
	{ "dooku_tcw/unrobed", ANIMSTYLE_COUNT_DOOKU },	// Count Dooku [TCW]
	{ "dooku_tcw", ANIMSTYLE_COUNT_DOOKU },	// Count Dooku [TCW - Robed]
	{ "dooku_dr", ANIMSTYLE_COUNT_DOOKU },	// Count Dooku [TCW - Dark Ritual]
	{ "dooku_pyjama", ANIMSTYLE_COUNT_DOOKU },	// Count Dooku [TCW - Pyjama]
	{ "dooku_pyjama/shoeless", ANIMSTYLE_COUNT_DOOKU },	// Count Dooku [TCW - Pyjama Shoeless]
	{ "dooku_totj", ANIMSTYLE_COUNT_DOOKU },	// Count Dooku [Tales of the Jedi]
	{ "darthmaul", ANIMSTYLE_MAUL },	// Darth Maul [Episode I]
	{ "darthmaul/robed", ANIMSTYLE_MAUL },	// Darth Maul [Robed]
	{ "darthmaul/hood", ANIMSTYLE_MAUL },	// Darth Maul [Hooded]
	{ "darthmaul/noshirt_gloves", ANIMSTYLE_MAUL },	// Darth Maul [Warrior]
	{ "maul_tcw", ANIMSTYLE_MAUL },	// Darth Maul [TCW]
	{ "maul_cyber_tcw", ANIMSTYLE_MAUL },	// Darth Maul [TCW - Reborn]
	{ "maul_rebels", ANIMSTYLE_MAUL },	// Darth Maul [Rebels]
	{ "maul_rebels/shirtless_hooded", ANIMSTYLE_MAUL },	// Darth Maul [Hooded]
	{ "maul_rebels/shirtless_cowelbase", ANIMSTYLE_MAUL },	// Darth Maul [Cowel]
	{ "maul_rebels/shirtless", ANIMSTYLE_MAUL },	// Darth Maul [Coweless]
	{ "maul_rebels/desert", ANIMSTYLE_MAUL },	// Darth Maul [Tatooine]
	{ "maul_rebels/twinsuns", ANIMSTYLE_MAUL },	// Darth Maul [Twin Suns Duel]
	{ "maul_tcw/solo", ANIMSTYLE_MAUL },	// Darth Maul [Crimson Dawn]
	{ "maul_tcw/solo_hood", ANIMSTYLE_MAUL },	// Darth Maul [Crimson Dawn - Hooded]
	{ "cyber_maul", ANIMSTYLE_MAUL },	// Darth Maul [Old Wounds]
	{ "cyber_maul/robed", ANIMSTYLE_MAUL },	// Darth Maul [Robed - Old Wounds]
	{ "cyber_maul/hood", ANIMSTYLE_MAUL },	// Darth Maul [Hooded - Old Wounds]
	{ "palpatine/senate", ANIMSTYLE_PALPATINE },	// Darth Sidious [Emperor]
	{ "palpatine/sith_hood", ANIMSTYLE_PALPATINE },	// Darth Sidious [Episode III]
	{ "palpatine/sith_hood2", ANIMSTYLE_PALPATINE },	// Darth Sidious [Episode III - Robed]
	{ "palpatine/robed_tcw", ANIMSTYLE_PALPATINE },	// Darth Sidious [TCW]
	{ "palpatine/robed", ANIMSTYLE_PALPATINE },	// Darth Sidious [Episode I-II]
	{ "palpatine", ANIMSTYLE_PALPATINE },	// Sheev Palpatine [Episode III]
	{ "grievous", ANIMSTYLE_GRIEVOUS },	// General Grievous [Episode III]
	{ "grievous/cape", ANIMSTYLE_GRIEVOUS },	// General Grievous [Robed]
	{ "jangofett", ANIMSTYLE_JANGO },	// Jango Fett [Episode II]
	{ "jangofett/jetpack2", ANIMSTYLE_JANGO },	// Jango Fett [Geonosis]
	{ "anakin/sith", ANIMSTYLE_ANAKIN },	// Lord Vader [Episode III]
	{ "anakin/srobed", ANIMSTYLE_ANAKIN },	// Lord Vader [Episode III - Robed]
	{ "anakin/shood", ANIMSTYLE_ANAKIN },	// Lord Vader [Episode III - Hooded]
	{ "anakin/smus", ANIMSTYLE_ANAKIN },	// Lord Vader [Episode III - Mustafar]
	{ "anakin/mortis", ANIMSTYLE_ANAKIN },	// Anakin Skywalker [TCW - Mortis]
	{ "magnaguard/utapau", ANIMSTYLE_BATTLEDROID },	// Magnaguard [Grievous's Bodyguard]
	{ "magnaguard/tcw", ANIMSTYLE_BATTLEDROID },	// Magnaguard [Dooku's Bodyguard]
	{ "gunray_ep3", ANIMSTYLE_MOVIEDUELS },	// Nute Gunray [Episode I-III]
	{ "asharad_hett", ANIMSTYLE_MOVIEDUELS },	// A'Sharad Hett [Legends]
	{ "asharad_hett/tusken", ANIMSTYLE_MOVIEDUELS },	// A'Sharad Hett [Tusken Mask]
	{ "obiwan_ot/default_robed", ANIMSTYLE_BENKENOBI },	// Ben Kenobi [Robed]
	{ "obiwan_ot/default_hooded", ANIMSTYLE_BENKENOBI },	// Ben Kenobi [Hooded]
	{ "obiwan_ot/ghost", ANIMSTYLE_BENKENOBI },	// Ben Kenobi [Force Ghost]
	{ "cade", ANIMSTYLE_ANAKIN },	// Cade Skywalker [Legends]
	{ "cal_kestis", ANIMSTYLE_CAL_KESTIS },	// Cal Kestis [Jedi Fallen Order]
	{ "cal_kestis/cape", ANIMSTYLE_CAL_KESTIS },	// Cal Kestis [Poncho]
	{ "cal_kestis/default2", ANIMSTYLE_CAL_KESTIS },	// Cal Kestis [Staff]
	{ "cal_kestis_jedi", ANIMSTYLE_CAL_KESTIS },	// Cal Kestis [Padawan]
	{ "cal_inquisitor", ANIMSTYLE_CAL_KESTIS },	// Inquisitor Kestis [Inquisitor]
	{ "cal_survivor", ANIMSTYLE_CAL_KESTIS },	// Cal Kestis [Jedi Survivor]
	{ "caleb_dume", ANIMSTYLE_MOVIEDUELS },	// Caleb Dume [Rebels]
	{ "caleb_dume/robed", ANIMSTYLE_MOVIEDUELS },	// Caleb Dume [Robed]
	{ "caleb_dume/hooded", ANIMSTYLE_MOVIEDUELS },	// Caleb Dume [Hooded]
	{ "ezrabridger", ANIMSTYLE_MOVIEDUELS },	// Ezra Bridger [Seasons 3-4]
	{ "stk_adventure_robes", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Jedi Adventure Robes]
	{ "stk_temple_eg", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Temple Exploration Gear]
	{ "stk_corellian_fs", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Corellian Flight Suit]
	{ "stk_ceremonial_robes", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Ceremonial Jedi Robes]
	{ "stk_tiepilot", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Tie Flightsuit]
	{ "stk_arena", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Arena Combat Gear]
	{ "stk_rebel_general", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Hero's Armor]
	{ "stk_kamino", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Test Subject Garments]
	{ "stk_kamino/clone", ANIMSTYLE_GALEN_MAREK },	// Galen Marek [Evil Clone Experiment]
	{ "jaro_tapal", ANIMSTYLE_CAL_KESTIS },	// Jaro Tapal [Jedi Fallen Order]
	{ "kanan", ANIMSTYLE_MOVIEDUELS },	// Kanan Jarrus [Rebels]
	{ "kanan/blind", ANIMSTYLE_MOVIEDUELS },	// Kanan Jarrus [Blind]
	{ "kentomarek", ANIMSTYLE_MOVIEDUELS },	// Kento Marek [TFU]
	{ "kentomarek/wii", ANIMSTYLE_MOVIEDUELS },	// Kento Marek [Alternate Design]
	{ "leia_anh", ANIMSTYLE_REBELS },	// Leia Organa [Princess]
	{ "luke_rotj", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi Knight]
	{ "luke_rotj/default_fd", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi Knight - Exposed Flap]
	{ "luke_rotj/endor", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Endor Camouflage]
	{ "luke_rotj/endor_nohelmet", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Endor Camouflage - Helmetless]
	{ "luke_rotj/tunic", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi - Tunic]
	{ "luke_rotj/tunic_robe", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi - Robed]
	{ "luke_rotj/tunic_hood", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi - Hooded]
	{ "luke_hoth", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Hoth]
	{ "luke_pilot", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Pilot]
	{ "luke_pilot/helmet", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Pilot - Helmet]
	{ "luke_pilot/sith", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Pilot - Sith]
	{ "luke_dago", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Dagobah]
	{ "luke_dago/backpack", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Dagobah - Yoda In Backpack]
	{ "luke_esb", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Bespin]
	{ "luke_esb/dirty", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Bespin - Dirty]
	{ "luke_esb/bw", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Bespin - Battleworn]
	{ "luke_esb/ds", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Bespin - Black]
	{ "luke_yavin", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Yavin Ceremony]
	{ "luke_anh", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Farm Boy]
	{ "luke_trainer/nobag", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi Master]
	{ "luke_trainer", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi Master - Grogu In Backpack]
	{ "luke_rotj/tm_robe", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi Master - Robed]
	{ "luke_rotj/tm_hood", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi Master - Hooded]
	{ "luke_rotj/bf2", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Battlefront 2]
	{ "luke_rotj/jka", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [JKA]
	{ "luke_rotj/master", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Jedi Master - TROKR]
	{ "luke_temple", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Pre-ROTJ - Temple]
	{ "luke_gm", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Grand Master]
	{ "luke_sote", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Shadows of the Empire]
	{ "luke_de", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Dark Empire]
	{ "luuke", ANIMSTYLE_LUKE_SKYWALKER },	// Luuke Skywalker [Evil Clone]
	{ "luuke/hood", ANIMSTYLE_LUKE_SKYWALKER },	// Luuke Skywalker [Evil Clone - Hooded]
	{ "kota", ANIMSTYLE_MOVIEDUELS },	// Rahm Kota [TFU]
	{ "kota_drunk", ANIMSTYLE_MOVIEDUELS },	// Rahm Kota [Drunken]
	{ "kota/blind", ANIMSTYLE_MOVIEDUELS },	// Rahm Kota [Alliance General]
	{ "rebel", ANIMSTYLE_REBELS },	// Rebel Alliance Trooper [Episode IV]
	{ "baylan", ANIMSTYLE_QUI_GON_JINN },	// Baylan Skoll [Ahsoka]
	{ "baylan/cape", ANIMSTYLE_QUI_GON_JINN },	// Baylan Skoll [Robed]
	{ "baylan/hood", ANIMSTYLE_QUI_GON_JINN },	// Baylan Skoll [Hooded]
	{ "boc", ANIMSTYLE_DARKFORCES2 },	// Boc [Dark Forces II]
	{ "darthkrayt", ANIMSTYLE_MOVIEDUELS },	// Darth Krayt [Emperor]
	{ "darthkrayt_r", ANIMSTYLE_MOVIEDUELS },	// Darth Krayt [Reborn]
	{ "darthphobos", ANIMSTYLE_MAUL },	// Darth Phobos [TFU]
	{ "darthvader/ep3", ANIMSTYLE_VADER },	// Darth Vader [Episode III]
	{ "darthvader/anh", ANIMSTYLE_VADER },	// Darth Vader [Episode IV]
	{ "darthvader", ANIMSTYLE_VADER },	// Darth Vader [Episode V-VI]
	{ "darthvader/tv", ANIMSTYLE_VADER },	// Darth Vader [Kenobi Damaged]
	{ "darthvader/battle", ANIMSTYLE_VADER },	// Darth Vader [Battle Damaged]
	{ "palpatine_fa", ANIMSTYLE_PALPATINE },	// Emperor Palpatine [Episode VI]
	{ "gorc", ANIMSTYLE_DARKFORCES2 },	// Gorc [Dark Forces II]
	{ "jerec/robed", ANIMSTYLE_DARKFORCES2 },	// Jerec [Dark Forces II]
	{ "jerec", ANIMSTYLE_DARKFORCES2 },	// Jerec [No Cape]
	{ "jerec/classic", ANIMSTYLE_DARKFORCES2 },	// Jerec [DF2 In-Game]
	{ "jerec_lowpoly", ANIMSTYLE_COUNT_DOOKU },	// Jerec [1997 Low Poly]
	{ "maw", ANIMSTYLE_DARKFORCES2 },	// Maw [Dismembered]
	{ "pic", ANIMSTYLE_DARKFORCES2 },	// Pic [Dark Forces II]
	{ "sariss", ANIMSTYLE_DARKFORCES2 },	// Sariss [Dark Forces II]
	{ "sariss/cape", ANIMSTYLE_DARKFORCES2 },	// Sariss [Cloaked]
	{ "shin", ANIMSTYLE_MOVIEDUELS },	// Shin Hati [Ahsoka]
	{ "shin/cloak", ANIMSTYLE_MOVIEDUELS },	// Shin Hati [Robed]
	{ "shin/hood", ANIMSTYLE_MOVIEDUELS },	// Shin Hati [Hooded]
	{ "stk_training_gear", ANIMSTYLE_GALEN_MAREK },	// Starkiller [TFU]
	{ "sithstalker", ANIMSTYLE_GALEN_MAREK },	// Starkiller [Sith Stalker Armor]
	{ "lord_stk", ANIMSTYLE_GALEN_MAREK },	// Lord Starkiller [TFU]
	{ "lord_stk_tat", ANIMSTYLE_GALEN_MAREK },	// Lord Starkiller [Tatooine]
	{ "gi_rebels", ANIMSTYLE_COUNT_DOOKU },	// The Grand Inquisitor [Rebels]
	{ "gi_rebels/jtguard_gi", ANIMSTYLE_COUNT_DOOKU },	// The Grand Inquisitor [Temple Guard]
	{ "yun", ANIMSTYLE_DARKFORCES2 },	// Yun [Dark Forces II]
	{ "finn", ANIMSTYLE_REY },	// Finn [TFA]
	{ "luke_tfa/cloak_glove", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Ach-to - Robed]
	{ "luke_tfa/hood_glove", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Ach-to - Hooded]
	{ "luke_crait", ANIMSTYLE_LUKE_SKYWALKER },	// Luke Skywalker [Crait Illusion]
	{ "nrep_sold", ANIMSTYLE_REBELS },	// New Republic Soldier [The Mandalorian]
	{ "nrsd", ANIMSTYLE_BATTLEDROID },	// New Republic Security Droid [The Mandalorian]
	{ "resistance/soldier", ANIMSTYLE_REBELS },	// Resistance Trooper [TFA]
	{ "resistance", ANIMSTYLE_REBELS },	// Resistance Trooper [TFA]
	{ "resistance/elite", ANIMSTYLE_REBELS },	// Resistance Trooper [TFA]
	{ "rey", ANIMSTYLE_REY },	// Rey [Jakku]
	{ "rey/resistance", ANIMSTYLE_REY },	// Rey [Resistance Scout]
	{ "rey/jedi", ANIMSTYLE_REY },	// Rey [Grey Jedi Wrap]
	{ "rey_skywalker", ANIMSTYLE_REY },	// Rey [White Jedi Wrap]
	{ "rey_skywalker/hood", ANIMSTYLE_REY },	// Rey [White Jedi Wrap - Hooded]
	{ "palpatine_ros", ANIMSTYLE_PALPATINE },	// Emperor Palpatine [Clone - Reborn]
	{ "palpatine_ros/blind", ANIMSTYLE_PALPATINE },	// Emperor Palpatine [Clone - Blind]
	{ "kylo_ren/nomask", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TFA - No Helmet]
	{ "kylo_ren/nohood", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TFA - Helmet]
	{ "kylo_ren", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TFA - Hooded]
	{ "kylo_ren/tlj_nomaskb", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TLJ - No Helmet]
	{ "kylo_ren/tlj", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TLJ - Helmet]
	{ "ben_swolo", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TLJ - Shirtless]
	{ "kylo_ren/tlj_nomaska", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TLJ - Robed]
	{ "kylo_ren/ros_nomask", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TROS - Robed]
	{ "kylo_ren/ros", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TROS - Helmet]
	{ "kylo_ren/ros_hood", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TROS - Hooded]
	{ "ben_solo", ANIMSTYLE_KYLO_REN },	// Kylo Ren [TROS - Redeemed]
	{ "matradartech", ANIMSTYLE_KYLO_REN },	// Kylo Ren [Matt the Radar Technician]
	{ "snoke", ANIMSTYLE_PALPATINE },	// Supreme Leader Snoke [TLJ]
};
